package com.quanvx.esim.constant.enums;

public enum EnumStatusOrder {
    INIT, SEND_JOYTEL_SUCCESS, SEND_JOYTEL_FAIL, GET_JOYTEL_QUERY_SUCCESS, GET_JOYTEL_QUERY_FAIL, SEND_MAIL_SUCCESS, SEND_MAIL_FAIL
}
