name: CI/CD for Spring Boot Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          java-package: jdk
          architecture: x64
          distribution: 'zulu'

      - name: Build the project
        run: ./mvnw clean install -DskipTests

      - name: Build Docker image
        run: docker build -t my-springboot-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-springboot-app ${{ secrets.DOCKER_USERNAME }}/my-springboot-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-springboot-app:latest

      - name: SSH to DigitalOcean Droplet and deploy the Docker container
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          script: |
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-springboot-app:latest
            
            # Copy docker-compose.yml to the droplet (make sure it exists in your GitHub repo)
            echo "Copying docker-compose.yml to the droplet..."
            scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.DIGITALOCEAN_USERNAME }}@${{ secrets.DIGITALOCEAN_HOST }}:/home/${{ secrets.DIGITALOCEAN_USERNAME }}/docker-compose.yml
            
            # Run the Docker container using docker-compose
            echo "Starting Docker container with docker-compose..."
            docker-compose -f docker-compose.yml up -d
